### ISSUE TITLE
file_field in form uploads as Http::UploadedFile

### ISSUE THREAD

**Issue by adziki** [atech/nifty-attachments#7]
I started the app without file, and added an attachment to my model afterwards.  I added the file_field to my form, and when I go to edit my models via the edit action I get this: 

ActiveRecord::AssociationTypeMismatch (Nifty::Attachments::Attachment(#70270868766960) expected, got ActionDispatch::Http::UploadedFile(#70270867955480)):

Any thoughts?

**Comment by adamcooke** [comment]
The field on the form should be suffixed with `_file`. If you had this model your field on the form should be named `photo_file`.

```ruby
class SomeModel
  attachment :photo
end
```

**Comment by adziki** [comment]
Model:
class Event < ActiveRecord::Base
	attachment :image
end

View form:
<div class="field">
      <%= f.label :image %><br>
      <%= f.image_file :image %>
    </div>

Gives me an error: undefined method `image_file'

**Comment by adziki** [comment]
oh, durr, should be: 
```
<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image_file %>
</div>
```
thanks!
